feature/pod-nft
IRISxiaowang/substrate-bank pull request #69
Opened 2024-04-08 09:33 UTC by IRISxiaowang

Close #62

Added buy_nft() and sell_nft() in pallet-bank.
Added trait ManageNfts
Added ensure_not_role() in trait ManageRoles

2024-04-12 02:58 UTC, IRISxiaowang commented
Moved pod from pallet-bank to pallet-nft

2024-04-12 22:28 UTC, syan095 commented on pallets/pallet-nft/src/lib.rs
> +		NftCanceled { nft_id: NftId, reason: UnlockReason },
maybe call this cancel reason

2024-04-12 22:29 UTC, syan095 commented on pallets/pallet-nft/src/lib.rs
> +	/// Stores the users' nft ids that will have their nft unlocked at a block.
this should be about expiry for POD pending delivery, not unlock

2024-04-16 00:33 UTC, syan095 commented on pallets/pallet-nft/src/lib.rs
> +		/// The nft id does not for POD.
clarify this

2024-04-16 00:34 UTC, syan095 commented on pallets/pallet-nft/src/lib.rs
> +		NftNotExist,
NftDoesNotExist

2024-04-16 00:35 UTC, syan095 commented on pallets/pallet-nft/src/lib.rs
> +		/// Emitted when an NFT creation is rejected by the auditor or the receiver rejected the
Should use a different event for when POD is rejected.
It represents a different scenario from when NFT MInt is rejected.

2024-04-16 00:36 UTC, syan095 commented on pallets/pallet-nft/src/lib.rs
> +		CancelReason { nft_id: NftId, reason: UnlockReason },
Rename this event

2024-04-16 00:39 UTC, syan095 commented on pallets/pallet-nft/src/lib.rs
> +			UnlockNft::<T>::take(block_number).into_iter().for_each(|(pod_id, nft_id)| {
Should rename this storage to something like PodExpiry
Avoid using "unlock/lock" for this, use "expire", cancel or "completed".

i.e.: "Ignore the cancel result - pod could be cancelled or completed prior to the expiry."

2024-04-16 00:43 UTC, syan095 commented on runtime/src/lib.rs
> +	type Fee = ConstU128<CENT>;
should allow higher MaxSize
and also use higher Fee (at least a dollar)
Rename Fee to something more clear - PodFee

2024-04-16 00:44 UTC, syan095 requested changes
Should add 3 Integration tests:
* created a POD and receiver accepted
* Receiver rejected
* Sender cancelled

2024-04-17 02:42 UTC, syan095 approved these changes

2024-04-17 03:25 UTC, merged